<a href="https://colab.research.google.com/github/yongpapunggon/papunggontaprasatsit_DTSC3020_summer2026/blob/main/TaprasatsitAssignment6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment 6 — File Handling, Data Processing, and Calculation

**Course:** DTSC 3020 — Introduction to Computation with Python  
**Covers:** Lesson 6 — file I/O, the `os`, `shutil`, and `csv` modules, NumPy arrays, and pandas DataFrames  
**Points:** 50 (5 problems, 10 points each)  
**Released:** Monday, July 6, 2026  
**Due:** Friday, July 10, 2026, at 11:59 PM CT

---

## Before you start

1. Make your own copy: **File → Save a copy in Drive**.
2. Rename the notebook using your last name first, for example: `SmithAssignment6.ipynb`.
3. In each answer cell, replace `Your Name` with your full name.

## Rules

- Use **meaningful variable names** and consistent indentation.
- Complete the problems in order. This notebook is self-contained: all required files are created by your code, but **Problem 2 uses the file created in Problem 1**.
- Do **not** manually upload any data files.
- Do **not hard-code** expected totals, counts, statistics, or filtered results. Calculate them from the provided data.
- Equivalent correct solutions are accepted unless a problem requires a specific function or method.
- Before submitting, select **Runtime → Restart and run all**. Every cell must run without errors from top to bottom.
- After running all cells, **save the notebook again** so that your outputs are visible in the submitted GitHub file.

## Grading

| Problem | Skill focus | Points |
|---|---|---:|
| 1 | Write, locate, and read a text file | 10 |
| 2 | Rename and copy a file safely | 10 |
| 3 | Write and read CSV data and calculate a total | 10 |
| 4 | Create and calculate with a NumPy array | 10 |
| 5 | Save, load, summarize, and filter data with pandas | 10 |

Each problem is generally graded as follows:

- **7 points:** correct code and logic
- **1 point:** required output and formatting
- **1 point:** conceptual comment
- **1 point:** readability and successful execution

## Submission

Push the completed notebook to GitHub using **File → Save a copy in GitHub**, then paste the GitHub URL in Canvas.


---


## Problem 1 — Write and Read a Text File *(10 points)*

Create a text file with Python, confirm that it exists, and read its contents.

### What to do

1. Import the `os` module.
2. Using a `with open(...)` block in **write mode** (`"w"`), create a file named `shop_notes.txt` containing exactly these three lines:

   ```text
   Eagle Beans daily log
   Lattes sold: 42
   Muffins sold: 17
   ```

   Add `"\n"` after each line so that the lines are stored separately. Use `encoding="utf-8"` when opening the file.
3. Use `os.path.exists("shop_notes.txt")` to confirm that the file exists and print the result.
4. Open the file in **read mode** (`"r"`) and print its full contents.
5. Open it once more, use `.readlines()` to count the lines, and print:

   ```text
   Line count: 3
   ```

6. Add a one-sentence **comment** explaining why `with open(...)` is preferred over manually calling `open()` and `close()`.

### Hints

- Write mode (`"w"`) creates a new file or overwrites an existing file.
- Read mode (`"r"`) reads an existing file.
- `os.path.exists(path)` returns `True` or `False`.
- `.read()` returns the entire file as one string.
- `.readlines()` returns a list in which each item represents one line.


In [1]:
# Papunggon Taprasatsit — Problem 1

import os
with open("shop_notes.txt", "w", encoding="utf-8") as file:
    file.write("Eagle Beans daily log\n")
    file.write("Lattes sold: 42\n")
    file.write("Muffins sold: 17\n")
exists_check = os.path.exists("shop_notes.txt")
print(exists_check)
with open("shop_notes.txt", "r", encoding="utf-8") as file:
    content = file.read()
    print(content)
with open("shop_notes.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()
    print(f"Line count: {len(lines)}")


# Using 'with open' is preferred because it automatically closes the file after the block finishes, preventing data loss or resource leaks even if an error occurs.


True
Eagle Beans daily log
Lattes sold: 42
Muffins sold: 17

Line count: 3


## Problem 2 — Rename and Copy a File *(10 points)*

Rename the file created in Problem 1 and make a backup copy. **Run Problem 1 before this problem.**

### What to do

1. Import `os` and `shutil`.
2. Use `os.rename(...)` to rename `shop_notes.txt` as `shop_log.txt`.
3. Use `os.path.exists(...)` to print the following checks:

   ```text
   Old name exists? False
   New name exists? True
   ```

4. Use `shutil.copy(...)` to create a backup named `shop_log_backup.txt`.
5. Print whether the backup exists.
6. Use `os.listdir(".")` to obtain the current folder contents. From that result, print the filenames `shop_log.txt` and `shop_log_backup.txt` so the grader can confirm that both exist. Other files in the folder do not need to be printed.
7. Add a one-sentence **comment** explaining the difference between renaming a file and copying a file.

### Hints

- `os.rename(old_name, new_name)` changes the filename; the old filename no longer remains.
- `shutil.copy(source, destination)` keeps the source file and creates a duplicate.
- `os.listdir(".")` returns the contents of the current folder.
- The order returned by `os.listdir(...)` is not guaranteed, so do not depend on a particular order.


In [2]:
# Papunggon Taprasatist — Problem 2

import os
import shutil

os.rename("shop_notes.txt", "shop_log.txt")

print(f"Old name exists? {os.path.exists('shop_notes.txt')}")
print(f"New name exists? {os.path.exists('shop_log.txt')}")

shutil.copy("shop_log.txt", "shop_log_backup.txt")

print(f"Backup exists? {os.path.exists('shop_log_backup.txt')}")

folder_contents = os.listdir(".")
if "shop_log.txt" in folder_contents:
    print("shop_log.txt")
if "shop_log_backup.txt" in folder_contents:
    print("shop_log_backup.txt")

# Renaming changes a file's name so the old name disappears, whereas copying leaves the original file completely unchanged and creates an identical duplicate.


Old name exists? False
New name exists? True
Backup exists? True
shop_log.txt
shop_log_backup.txt


## Problem 3 — Work with a CSV File *(10 points)*

Write tabular data to a CSV file, read it back, and calculate total sales.

### What to do

1. Import the `csv` module.
2. Using `csv.writer`, create a file named `sales.csv` with the following header and data rows:

   ```text
   item,qty,price
   latte,3,4.50
   muffin,2,3.25
   mocha,1,5.00
   ```

   Open the file with `newline=""` and `encoding="utf-8"` when writing.
3. Open `sales.csv` with `csv.reader`.
4. Read and store the header using `next(reader)`.
5. Loop through the remaining rows and calculate:

   ```text
   total_sales = sum of (quantity × price) for all rows
   ```

   CSV values are read as strings, so convert quantity with `int(...)` and price with `float(...)`.
6. Print the header and print the total formatted as money:

   ```text
   Total sales: $25.00
   ```

7. Add a one-sentence **comment** explaining why CSV values must be converted before performing numerical calculations.

### Hints

- `writer.writerows(rows)` writes multiple rows.
- `next(reader)` reads the next row and moves the reader forward.
- `int("3") * float("4.50")` performs numerical multiplication.
- Do not directly print `$25.00`; calculate the total from the rows.


In [3]:
# Papunggon Taprasatsit — Problem 3
import csv


rows = [
    ["item", "qty", "price"],
    ["latte", "3", "4.50"],
    ["muffin", "2", "3.25"],
    ["mocha", "1", "5.00"]
]

with open("sales.csv", "w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerows(rows)


with open("sales.csv", "r", encoding="utf-8") as file:
    reader = csv.reader(file)


    header = next(reader)

    total_sales = 0.0
    for row in reader:
        quantity = int(row[1])
        price = float(row[2])
        total_sales += quantity * price

print(header)
print(f"Total sales: ${total_sales:.2f}")

# CSV values are read as strings by default, so they must be explicitly converted to integers or floats before performing mathematical operations to avoid errors or unintended text repetition.


['item', 'qty', 'price']
Total sales: $25.00


## Problem 4 — Calculations with NumPy *(10 points)*

Use a NumPy array to perform numerical calculations without writing loops.

### What to do

1. Import NumPy using the standard alias: `import numpy as np`.
2. Create the following NumPy array of daily high temperatures in degrees Fahrenheit:

   ```python
   temps = np.array([68, 72, 70, 74, 69, 73, 71])
   ```

3. Print each result with a clear label:

   - mean: `71.0`
   - maximum: `74`
   - minimum: `68`
   - population standard deviation, rounded to two decimal places: `2.0`

4. Use **Boolean indexing** to select temperatures greater than 71. Print the selected values and their count.

   Expected values:

   ```text
   [72 74 73]
   Count: 3
   ```

5. Use one **vectorized expression** to convert all Fahrenheit values to Celsius:

   ```text
   Celsius = (Fahrenheit - 32) × 5 / 9
   ```

   Round the resulting array to one decimal place and print it. Do not use a loop.

   Expected result:

   ```text
   [20.  22.2 21.1 23.3 20.6 22.8 21.7]
   ```

6. Add a one-sentence **comment** naming one advantage of a NumPy array over a Python list for numerical work.

### Hints

- `np.array([...])` creates a NumPy array.
- You may use either NumPy functions, such as `np.mean(temps)`, or equivalent array methods, such as `temps.mean()`.
- `temps > 71` creates a Boolean array.
- `temps[temps > 71]` keeps only values whose Boolean positions are `True`.
- `np.round(array, 1)` rounds each element to one decimal place.


In [4]:
# Papunggon Taprasatsit — Problem 4
import numpy as np


temps = np.array([68, 72, 70, 74, 69, 73, 71])


print(f"mean: {np.mean(temps)}")
print(f"maximum: {np.max(temps)}")
print(f"minimum: {np.min(temps)}")
print(f"population standard deviation, rounded to two decimal places: {np.round(np.std(temps), 2)}")


hot_temps = temps[temps > 71]
print(hot_temps)
print(f"Count: {len(hot_temps)}")


celsius = np.round((temps - 32) * 5 / 9, 1)
print(celsius)


# NumPy arrays support vectorized operations, allowing mathematical operations to be executed on entire datasets simultaneously without using manual loops.


mean: 71.0
maximum: 74
minimum: 68
population standard deviation, rounded to two decimal places: 2.0
[72 74 73]
Count: 3
[20.  22.2 21.1 23.3 20.6 22.8 21.7]


## Problem 5 — Save, Load, and Analyze Data with pandas *(10 points)*

Create a pandas DataFrame, save it as a CSV file, load it again, and answer questions about the data.

### What to do

1. Import pandas using the standard alias: `import pandas as pd`.
2. Create a DataFrame from the following dictionary:

   ```python
   data = {
       "name":  ["Maria", "Devon", "Aisha", "Carlos", "Lena"],
       "drink": ["latte", "mocha", "latte", "espresso", "mocha"],
       "spent": [12.50, 9.00, 15.25, 4.50, 9.00],
   }
   ```

3. Store the first DataFrame in a meaningfully named variable such as `customer_data`.
4. Save it as `customers.csv` using `.to_csv(..., index=False)`.
5. Load `customers.csv` with `pd.read_csv(...)` and store the loaded DataFrame in `df`.
6. Print the complete loaded DataFrame.
7. Print each result with a clear label:

   - shape: `(5, 3)`
   - total spent: `$50.25`
   - average spent, rounded to two decimal places: `$10.05`

8. Filter `df` to show only the `name` and `spent` columns for customers who spent **more than $10**. The result should contain Maria and Aisha.
9. Use `df["drink"].value_counts()` to print the number of customers who ordered each drink.
10. Add a one-sentence **comment** explaining the difference between a pandas DataFrame and a pandas Series.

### Hints

- `pd.DataFrame(data)` creates a table from a dictionary.
- `df.to_csv("customers.csv", index=False)` prevents pandas from saving an extra index column.
- `pd.read_csv("customers.csv")` loads a CSV file as a DataFrame.
- `df[df["spent"] > 10][["name", "spent"]]` filters rows and selects columns.
- `value_counts()` may display categories with equal counts in a different order. Correct counts matter more than order.


In [5]:
# Papunggon Taprasatsit — Problem 5
import pandas as pd

data = {
    "name": ["Maria", "Devon", "Aisha", "Carlos", "Lena"],
    "drink": ["latte", "mocha", "latte", "espresso", "mocha"],
    "spent": [12.50, 9.00, 15.25, 4.50, 9.00],
}

customer_data = pd.DataFrame(data)

customer_data.to_csv("customers.csv", index=False)

df = pd.read_csv("customers.csv")

print(df)
print()

print(f"shape: {df.shape}")
print(f"total spent: ${df['spent'].sum():.2f}")
print(f"average spent, rounded to two decimal places: ${df['spent'].mean():.2f}")
print()

filtered_df = df[df["spent"] > 10][["name", "spent"]]
print(filtered_df)
print()

print(df["drink"].value_counts())
print()


# A pandas DataFrame represents a complete two-dimensional table with rows and columns, whereas a pandas Series represents a single one-dimensional column from that table.


     name     drink  spent
0   Maria     latte  12.50
1   Devon     mocha   9.00
2   Aisha     latte  15.25
3  Carlos  espresso   4.50
4    Lena     mocha   9.00

shape: (5, 3)
total spent: $50.25
average spent, rounded to two decimal places: $10.05

    name  spent
0  Maria  12.50
2  Aisha  15.25

drink
latte       2
mocha       2
espresso    1
Name: count, dtype: int64

